site_name: Marketplace Documentation
theme:
  name: material
nav:
  - Home: index.md
  - Features: feature.md
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.superfences
